# Generated by Django 5.1.2 on 2024-11-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_episode_created_at_episode_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='updated_at',
        ),
    ]
