# Generated by Django 5.1.2 on 2024-12-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_episode_image_playlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
    ]
